LabNB/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from LabNB import views     # This lets us use the custom error handlers, as well as an index view with context, if desired.

# These handlers override the default error page provided by Django.
# Django looks for these var names specifically in the urlconf.

handler404 = 'LabNB.views.page_not_found'
handler500 = 'LabNB.views.server_error'

# Added for simple templates like homepage, or icons
from django.views.generic import TemplateView, RedirectView

# URLs
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'LabNB.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # http://stackoverflow.com/questions/1940528/django-index-page-best-most-common-practice

    # OMG CRAZY NOTE: namespace ABSOLUTELY MUST BE IN DOUBLEQUOTES to work.
    
    url(r'^$', views.index, name='index'),
    url(r'accounts/login/', 'django.contrib.auth.views.login'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^labinv/', include('labinv.urls', namespace="labinv")),
    url(r'^data/', include('data.urls', namespace="data")),
    url(r'^apple-touch-icon\.png$', RedirectView.as_view(
        url='%simg/apple-touch-icon.png' % settings.STATIC_URL)),
    url(r'^crossdomain\.xml$', TemplateView.as_view(
	   template_name='crossdomain.xml')),
    url(r'^favicon\.ico$', RedirectView.as_view(
	   url='%simg/favicon.ico' % settings.STATIC_URL)),
    url(r'^humans\.txt', TemplateView.as_view(
	   template_name='humans.txt')),
	url(r'^robots\.txt', TemplateView.as_view(
		template_name='robots.txt')),
)

urlpatterns += patterns('', (
        r'^static/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}
))

urlpatterns += patterns('',
               (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                 {'document_root': settings.MEDIA_ROOT}),
              )

data/urls.py
from django.conf.urls import patterns,url
from data import views
from django.conf import settings
from django.contrib.auth.decorators import login_required

# To use url tag in template, use something like {% url 'data:URLNAME' %}

urlpatterns = patterns('',
	# url(r'accounts/login/', 'django.contrib.auth.views.login'),
	url(r'^$', views.index, name='index'),
	url(r'^inxSurvExp/$', views.inxSurvExpList, name='inxSurvExp-list'),
	url(r'^inxSurvExp/create$', login_required(views.inxSurvExpCreateView.as_view()), name='inxSurvExp-create'),
	url(r'^inxSurvExp/(?P<pk>\d+)/inxsurvplot.png$', views.inxSurvExpPlot, name='inxSurvExp-plot'),
	url(r'^inxSurvExp/(?P<pk>\d+)$', views.inxSurvExpDetail, name='inxSurvExp-detail'),
	url(r'^inxSurvExp/(?P<pk>\d+)/update$', login_required(views.inxSurvExpUpdateView.as_view()), name='inxSurvExp-update'),
	url(r'^inxSurvExp/(?P<pk>\d+)/delete$', login_required(views.inxSurvExpDeleteView.as_view()), name='inxSurvExp-delete'),
	url(r'^survExp/$', views.survExpList, name='survExp-list'),
	url(r'^survExp/create$', login_required(views.survExpCreateView.as_view()), name='survExp-create'),
	url(r'^survExp/(?P<pk>\d+)/survplot.png$', views.survExpPlot, name='survExp-plot'),
	url(r'^survExp/(?P<pk>\d+)$', views.survExpDetail, name='survExp-detail'),
	url(r'^survExp/(?P<pk>\d+)/update$', login_required(views.survExpUpdateView.as_view()), name='survExp-update'),
	url(r'^survExp/(?P<pk>\d+)/delete$', login_required(views.survExpDeleteView.as_view()), name='survExp-delete'),
	url(r'^uInx/$', views.uInxList, name='uInx-list'),
	url(r'^uInx/create$', login_required(views.uInxCreateView.as_view()), name='uInx-create'),
	url(r'^uInx/(?P<pk>\d+)$', views.uInxDetail, name='uInx-detail'),
	url(r'^uInx/(?P<pk>\d+)/update$', login_required(views.uInxUpdateView.as_view()), name='uInx-update'),
	url(r'^uInx/(?P<pk>\d+)/delete$', login_required(views.uInxDeleteView.as_view()), name='uInx-delete'),
	url(r'^exp/$', views.miscExpList, name='exp-list'),
	url(r'^exp/create$', login_required(views.miscExpCreateView.as_view()), name='exp-create'),
	url(r'^exp/(?P<pk>\d+)$', views.miscExpDetail, name='exp-detail'),
	url(r'^exp/(?P<pk>\d+)/update$', login_required(views.miscExpUpdateView.as_view()), name='exp-update'),
	url(r'^exp/(?P<pk>\d+)/delete$', login_required(views.miscExpDeleteView.as_view()), name='exp-delete'),
	url(r'^gel/$', views.gelList, name='gel-list'),
	url(r'^gel/create$', login_required(views.gelCreateView.as_view()), name='gel-create'),
	url(r'^gel/(?P<pk>\d+)$', views.gelDetail, name='gel-detail'),
	url(r'^gel/(?P<pk>\d+)/update$', login_required(views.gelUpdateView.as_view()), name='gel-update'),
	url(r'^gel/(?P<pk>\d+)/delete$', login_required(views.gelDeleteView.as_view()), name='gel-delete'),
	url(r'^img/$', views.miscImgList, name='img-list'),
	url(r'^img/create$', login_required(views.miscImgCreateView.as_view()), name='img-create'),
	url(r'^img/(?P<pk>\d+)$', views.miscImgDetail, name='img-detail'),
	url(r'^img/(?P<pk>\d+)/update$', login_required(views.miscImgUpdateView.as_view()), name='img-update'),
	url(r'^img/(?P<pk>\d+)/delete$', login_required(views.miscImgDeleteView.as_view()), name='img-delete'),
	url(r'^file/$', views.miscFileList, name='file-list'),
	url(r'^file/create$', login_required(views.miscFileCreateView.as_view()), name='file-create'),
	url(r'^file/(?P<pk>\d+)$', views.miscFileDetail, name='file-detail'),
	url(r'^file/(?P<pk>\d+)/update$', login_required(views.miscFileUpdateView.as_view()), name='file-update'),
	url(r'^file/(?P<pk>\d+)/delete$', login_required(views.miscFileDeleteView.as_view()), name='file-delete'),
	url(r'^custom/querydata$',views.queryData,name='querydata'),
	)

urlpatterns += patterns('', (
        r'^static/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}
)
)

urlpatterns += patterns('',
               (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                 {'document_root': settings.MEDIA_ROOT}),
              )

labinv/urls.py
from django.conf.urls import patterns,url
from labinv import views
from django.contrib.auth.decorators import login_required

# To use url tag in template, use something like {% url 'labinv:URLNAME' %}
urlpatterns = patterns('',
	# url(r'accounts/login/', 'django.contrib.auth.views.login'),
	url(r'^$', views.index, name='index'),
	url(r'^gRNA/$', views.gRNAList, name='gRNA-list'),
	url(r'^gRNA/create$', login_required(views.gRNACreateView.as_view()), name='gRNA-create'),
	url(r'^gRNA/(?P<pk>\d+)$',views.gRNADetail, name='gRNA-detail'),
	url(r'^gRNA/(?P<pk>\d+)/update$',login_required(views.gRNAUpdateView.as_view()), name='gRNA-update'),
	url(r'^gRNA/(?P<pk>\d+)/delete$',login_required(views.gRNADeleteView.as_view()), name='gRNA-delete'),
	url(r'^cas9/$', views.cas9List, name='cas9-list'),
	url(r'^cas9/create$', login_required(views.cas9CreateView.as_view()), name='cas9-create'),
	url(r'^cas9/(?P<pk>\d+)$',views.cas9Detail, name='cas9-detail'),
	url(r'^cas9/(?P<pk>\d+)/update$',login_required(views.cas9UpdateView.as_view()), name='cas9-update'),
	url(r'^cas9/(?P<pk>\d+)/delete$',login_required(views.cas9DeleteView.as_view()), name='cas9-delete'),
	url(r'^strip/$', views.stripList, name='strip-list'),
	url(r'^strip/create$', login_required(views.stripCreateView.as_view()), name='strip-create'),
	url(r'^strip/(?P<pk>\d+)$',views.stripDetail, name='strip-detail'),
	url(r'^strip/(?P<pk>\d+)/update$',login_required(views.stripUpdateView.as_view()), name='strip-update'),
	url(r'^strip/(?P<pk>\d+)/delete$',login_required(views.stripDeleteView.as_view()), name='strip-delete'),
	url(r'^tube/$', views.tubeList, name='tube-list'),
	url(r'^tube/create$', login_required(views.tubeCreateView.as_view()), name='tube-create'),
	url(r'^tube/(?P<pk>\d+)$',views.tubeDetail, name='tube-detail'),
	url(r'^tube/(?P<pk>\d+)/update$',login_required(views.tubeUpdateView.as_view()), name='tube-update'),
	url(r'^tube/(?P<pk>\d+)/delete$',login_required(views.tubeDeleteView.as_view()), name='tube-delete'),
	)

data/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import Context, loader

from django.views.generic import CreateView,UpdateView,DeleteView,TemplateView

from .models import *
from .forms import *

from django.contrib.auth.decorators import login_required 

# Create your views here.

@login_required
def index(request):
	t = loader.get_template('data/dataindex.html')
	C=Context()
	return HttpResponse(t.render(C))

###################################################################################################

# Experiments

###################################################################################################

################################
# inxSurvival Experiment views #
################################

@login_required
def inxSurvExpList(request):
	t=loader.get_template('data/inxSurvExpList.html')
	inxSurvExps=inxSurvivalExp.objects.all()
	C=Context({'inxSurvExps': inxSurvExps})
	# consider calculating additional context variables in the future, for utility, such as survival %s
	return HttpResponse(t.render(C))
	
class inxSurvExpCreateView(CreateView):
    model = inxSurvivalExp
    success_url='/data/inxSurvExp/'

class inxSurvExpUpdateView(UpdateView):
	model = inxSurvivalExp
	success_url='/data/inxSurvExp/'

class inxSurvExpDeleteView(DeleteView):
	model = survivalExp
	success_url='/data/inxSurvExp/'

@login_required
def inxSurvExpPlot(request,pk):
	import random
	import django
	import pandas as pd
	from re import split
	from lifelines.utils import survival_events_from_table
	from lifelines import KaplanMeierFitter
	from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
	from matplotlib.figure import Figure

	thisinxSurvExp=inxSurvivalExp.objects.get(pk=pk)
	# without wasting variables, this converts the comma-separated string into an int list
	dailyDeathsExp=[int(deathExp) for deathExp in split(',',thisinxSurvExp.dailyDeathsExp)]
	expFinalSurviving=thisinxSurvExp.nInx-sum(dailyDeathsExp)
	dailyDeathsExp.append(expFinalSurviving)
	dailyDeathsCtrl=[int(deathCtrl) for deathCtrl in split(',',thisinxSurvExp.dailyDeathsCtrl)]
	ctrlFinalSurviving=thisinxSurvExp.nCtrl-sum(dailyDeathsCtrl)
	dailyDeathsCtrl.append(ctrlFinalSurviving)
	# we need a way for lifelines to understand that not all of our fish died by 7dpf, so we use the 
	# censorship parameter to say that the last element in this list represents the number of surviving 
	# fish for the experiment.
	censorHack=[0]*(len(dailyDeathsExp)-1)
	censorHack.append(1)

	expSurvival=pd.DataFrame({'Texp':dailyDeathsExp,'Cexp':censorHack})
	Texp,Cexp=survival_events_from_table(expSurvival,observed_deaths_col='Texp',censored_col='Cexp')

	ctrlSurvival=pd.DataFrame({'Tctrl':dailyDeathsCtrl,'Cctrl':censorHack})
	Tctrl,Cctrl=survival_events_from_table(ctrlSurvival,observed_deaths_col='Tctrl',censored_col='Cctrl')

	# plotting to image happens here.
	fig=Figure()
	ax=fig.add_subplot(111)

	kmfExp=KaplanMeierFitter()
	ax=kmfExp.fit(Texp,event_observed=Cexp,label=thisinxSurvExp.inx.gRNA.geneTarget+' injected\nn = '+str(thisinxSurvExp.nInx)).plot(ax=ax)

	kmfCtrl=KaplanMeierFitter()
	ax=kmfCtrl.fit(Tctrl,event_observed=Cctrl,label=thisinxSurvExp.ctrlType+'\nn = '+str(thisinxSurvExp.nCtrl)).plot(ax=ax)
	ax.set_ylabel('Fraction Surviving')
	ax.set_xlabel('Days post-fertilization')

	canvas=FigureCanvas(fig)
	response=HttpResponse(content_type='image/png')
	canvas.print_png(response)
	return response	

@login_required
def inxSurvExpDetail(request,pk):
	t=loader.get_template('data/inxsurvexpdetail.html')
	thisinxSurvExp=survivalExp.objects.get(pk=pk)
	C=Context({'inxSurvExp': thisinxSurvExp})
	return HttpResponse(t.render(C))

#############################
# Survival Experiment views #
#############################

@login_required
def survExpList(request):
	t=loader.get_template('data/survExpList.html')
	survExps=survivalExp.objects.all()
	C=Context({'survExps': survExps})
	return HttpResponse(t.render(C))
	
class survExpCreateView(CreateView):
    model = survivalExp
    success_url='/data/survExp/'

class survExpUpdateView(UpdateView):
	model = survivalExp
	success_url='/data/survExp/'

class survExpDeleteView(DeleteView):
	model = survivalExp
	success_url='/data/survExp/'

@login_required
def survExpPlot(request,pk):
	import random
	import django
	import pandas as pd
	from re import split
	from lifelines.utils import survival_events_from_table
	from lifelines import KaplanMeierFitter
	from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
	from matplotlib.figure import Figure

	thisSurvExp=survivalExp.objects.get(pk=pk)
	# without wasting variables, this converts the comma-separated string into an int list
	dailyDeathsExp=[int(deathExp) for deathExp in split(',',thisSurvExp.dailyDeathsExp)]
	expFinalSurviving=thisSurvExp.nExp-sum(dailyDeathsExp)
	dailyDeathsExp.append(expFinalSurviving)
	# we need a way for lifelines to understand that not all of our fish died by 7dpf, so we use the 
	# censorship parameter to say that the last element in this list represents the number of surviving 
	# fish for the experiment.
	censorHack=[0]*(len(dailyDeathsExp)-1)
	censorHack.append(1)

	expSurvival=pd.DataFrame({'Texp':dailyDeathsExp,'Cexp':censorHack})
	Texp,Cexp=survival_events_from_table(expSurvival,observed_deaths_col='Texp',censored_col='Cexp')

	# plotting to image happens here.
	fig=Figure()
	ax=fig.add_subplot(111)

	kmfExp=KaplanMeierFitter()
	ax=kmfExp.fit(Texp,event_observed=Cexp,label=str(thisSurvExp)+'\nn = '+str(thisSurvExp.nExp)).plot(ax=ax)
	ax.set_ylabel('Fraction Surviving')

	canvas=FigureCanvas(fig)
	response=HttpResponse(content_type='image/png')
	canvas.print_png(response)
	return response	

@login_required
def survExpDetail(request,pk):
	t=loader.get_template('data/survexpdetail.html')
	thisSurvExp=survivalExp.objects.get(pk=pk)
	C=Context({'survExp': thisSurvExp})
	return HttpResponse(t.render(C))

###############################
# uInjection Experiment views #
###############################

@login_required
def uInxList(request):
	t=loader.get_template('data/uinxlist.html')
	uInjections=uInjection.objects.all()
	C=Context({'uInjections': uInjections})
	return HttpResponse(t.render(C))

class uInxCreateView(CreateView):
    model = uInjection
    success_url='/data/uInx/'

class uInxUpdateView(UpdateView):
	model = uInjection
	success_url='/data/uInx/'

class uInxDeleteView(DeleteView):
	model = uInjection
	success_url='/data/uInx/'

@login_required
def uInxDetail(request,pk):
	t=loader.get_template('data/uinxdetail.html')
	thisUInx=survivalExp.objects.get(pk=pk)
	C=Context({'uInx': thisUInx})
	return HttpResponse(t.render(C))
    
########################
# miscExperiment views #
########################

@login_required
def miscExpList(request):
	t=loader.get_template('data/miscExpList.html')
	miscExps=miscExp.objects.all()
	C=Context({'miscExps': miscExps})
	return HttpResponse(t.render(C))

class miscExpCreateView(CreateView):
    model = miscExp
    success_url='/data/exp/'

class miscExpUpdateView(UpdateView):
	model = miscExp
	success_url='/data/exp/'

class miscExpDeleteView(DeleteView):
	model = miscExp
	success_url='/data/exp/'

@login_required
def miscExpDetail(request,pk):
	t=loader.get_template('data/miscexpdetail.html')
	thisMiscExp=miscExp.objects.get(pk=pk)
	C=Context({'miscExp': thisMiscExp})
	return HttpResponse(t.render(C))

###################################################################################################

# Images and other Files

###################################################################################################

#############
# gel views #
#############

@login_required
def gelList(request):
	t=loader.get_template('data/gelList.html')
	gels=gel.objects.all()
	C=Context({'gels': gels})
	return HttpResponse(t.render(C))

class gelCreateView(CreateView):
    model = gel
    success_url='/data/gel/'

class gelUpdateView(UpdateView):
	model = gel
	success_url='/data/gel/'

class gelDeleteView(DeleteView):
	model = gel
	success_url='/data/gel/'

@login_required
def gelDetail(request,pk):
	t=loader.get_template('data/geldetail.html')
	thisGel=gel.objects.get(pk=pk)
	C=Context({'gel': thisGel})
	return HttpResponse(t.render(C))

#################
# miscImg views #
#################

@login_required
def miscImgList(request):
	t=loader.get_template('data/miscImgList.html')
	miscImgs=miscImg.objects.all()
	C=Context({'miscImgs': miscImgs})
	return HttpResponse(t.render(C))

class miscImgCreateView(CreateView):
    form_class = ImgUploadModelForm
    template_name = 'data/miscimg_form.html'
    success_url='/data/img/'

class miscImgUpdateView(UpdateView):
	model = miscImg
	success_url='/data/img/'

class miscImgDeleteView(DeleteView):
	model = miscImg
	success_url='/data/img/'

@login_required
def miscImgDetail(request,pk):
	t=loader.get_template('data/miscImgdetail.html')
	thisMiscImg=miscImg.objects.get(pk=pk)
	C=Context({'miscImg': thisMiscImg})
	return HttpResponse(t.render(C))

##################
# miscFile views #
##################

@login_required
def miscFileList(request):
	t=loader.get_template('data/miscFileList.html')
	miscFiles=miscFile.objects.all()
	C=Context({'miscFiles': miscFiles})
	return HttpResponse(t.render(C))

class miscFileCreateView(CreateView):
    model = miscFile
    success_url='/data/file/'

class miscFileUpdateView(UpdateView):
	model = miscFile
	success_url='/data/file/'

class miscFileDeleteView(DeleteView):
	model = miscFile
	success_url='/data/file/'

@login_required
def miscFileDetail(request,pk):
	t=loader.get_template('data/miscfiledetail.html')
	thisMiscFile=miscFile.objects.get(pk=pk)
	C=Context({'miscFile': thisMiscFile})
	return HttpResponse(t.render(C))

###################################################################################################

# Custom views for specific functions

data/templates/data/dataindex.html
{% extends "base.html" %}

{% block title %}Data Home{% endblock title %}

{% block content %}
	<div class="container">
		<div class="row">
			<h1>What new data do you have for me today?</h1> 
		</div>
	<hr>
		<div class="row">
			<h2>Experiments</h2>
			<div class="col-md-3">
				<h3>Microinjection</h3>
				<p>
				<a class="btn btn-primary btn-md" href="/data/uInx" role="button">View All &raquo;</a>
				<a class="btn btn-primary btn-md" href="/data/uInx/create" role="button">Add &raquo;</a>
				</p>
			</div>
			<div class="col-md-3">
				<h3>Injection survival</h3>
				<p>
				<a class="btn btn-primary btn-md" href="/data/inxSurvExp" role="button">View All &raquo;</a>
				<a class="btn btn-primary btn-md" href="/data/inxSurvExp/create" role="button">Add &raquo;</a>
				</p>
			</div>
			<div class="col-md-3">
				<h3>Other survival</h3>
				<p>
				<a class="btn btn-primary btn-md" href="/data/survExp" role="button">View All &raquo;</a>
				<a class="btn btn-primary btn-md" href="/data/survExp/create" role="button">Add &raquo;</a>
				</p>
			</div>
			<div class="col-md-3">
				<h3>Other experiment</h3>
				<p>
				<a class="btn btn-primary btn-md" href="/data/exp" role="button">View All &raquo;</a>
				<a class="btn btn-primary btn-md" href="/data/exp/create" role="button">Add &raquo;</a>
				</p>
			</div>
		</div>
		<hr>
		<div class="row">
			<h2>Data files</h2>
			<div class="col-md-4">
				<h3>Gel</h3>
				<p>
				<a class="btn btn-primary btn-md" href="/data/gel" role="button">View All &raquo;</a>
				<a class="btn btn-primary btn-md" href="/data/gel/create" role="button">Add &raquo;</a>
				</p>
			</div>
			<div class="col-md-4">
				<h3>Other Image</h3>
				<p>
				<a class="btn btn-primary btn-md" href="/data/img" role="button">View All &raquo;</a>
				<a class="btn btn-primary btn-md" href="/data/img/create" role="button">Add &raquo;</a>
				</p>
			</div>
			<div class="col-md-4">
				<h3>Other File</h3>
				<p>
				<a class="btn btn-primary btn-md" href="/data/file" role="button">View All &raquo;</a>
				<a class="btn btn-primary btn-md" href="/data/file/create" role="button">Add &raquo;</a>
				</p>
			</div>
		</div>
		{{ block.super }}
	</div>
{% endblock content %}

data/templates/data/gel_confirm_delete.html
{% extends "base.html" %}

{% block title %}Delete {{object}}{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
	<h2>Delete "{{ object }}"</h2>
	<hr>
	<p>Are you sure you want to do this?</p>
		<form method="POST">{% csrf_token %}
    		{{ form.as_p}}
    		<button type="submit" value="Confirm">Delete</button>
		</form>
	</div>
	{{block.super}}
</div>
{% endblock %}

data/templates/data/inxsurvivalexp_update_form.html
{% extends "base.html" %}

{% block title %}Update {{object}}{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
	<h2>Update "{{ object }}"</h2>
	<hr>
		<form method="POST">{% csrf_token %}
    		{{ form.as_p}}
    		<button type="submit" value="Update">Update</button>
		</form>
	</div>
	{{block.super}}
</div>
{% endblock %}

data/templates/data/miscFileList.html
{% extends "base.html" %}

{% block title %}Lab Notebook - Data - Misc File{% endblock title %}

{% block content %}
<div class="container">
	<div class="row">
	<h1>All Miscellaneous Files</h1>
		<table class="table table-hover">
			<thead>
				<tr>
					<th>Name</th>
					<th>Date</th>
				</tr>
			</thead>
			<tbody>
				{% for miscFile in miscFiles %}
					<tr>
						<td><a href="/data/file/{{ miscFile.pk }}">{{ miscFile.shortName }}</a></td>
						<td>{{ miscFile.date|date:'d M Y' }}</td>
					</tr>
				{% empty %}
				<p>No images yet</p>
				{% endfor %}
			</tbody>
		</table>
	</div>
	<div class="row">
		<a class="btn btn-primary btn-lg" href="/data/file/create" role="button">Add a miscellaneous image &raquo;</a>
	</div>
	{{block.super}}
</div>
{% endblock content %}

data/templates/data/querydata.html
{% extends "base.html" %}

{% block title %}Data summary{% endblock %}

{% block content %}
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>Query Data</h1>
<div class="input-group">
	<form method="get" action="{% url 'data:querydata' %}">
	{% csrf_token %}
	<input type="text" class="form-control" size=50 name="query" placeholder="Comma-separated list of genes you care about"/>
	<span class="input-group-btn">
		<button class="btn btn-default" type="button">Search</button>
	</span>
	</form>
</div>
</div>
</div>
{% if queryString %}
<div class="row" style="margin-top:1%;">
<div class="col-md-12">
{% if badQueries %}
<div class="panel panel-warning">
	<div class="panel-heading">
	<h3 class="panel-title">Queries not found</h3>
	</div>
	<div class="panel-body">
	<p>You had some geneTargets we couldn't find. These are either bad queries, or there have been no gRNAs created for these targets.</p>
	<ul class="list-group">
	{% for badQuery in badQueries %}
	<li class="list-group-item">{{badQuery}}</li>
	{% endfor %}
	</ul>
	</div>
</div>
{% endif %}
<div class="panel panel-default">
	<div class="panel-heading">
	<h3 class="panel-title">Search Results for: "{{queryString}}"</h3>
	</div>
	<div class="panel-body">
	{% if goodQueries %}
	<ul class="list-group">
		{% for query,inxDict in goodQueries.items %}
			<li class="list-group-item">
			<h4><a href="{% url 'labinv:gRNA-detail' query.pk %}">{{query}}</a></h4>
			{% if inxDict %}
			<table class="table">
			<thead>
			<th>Date(s) injected</th>
			<th># Injected (survival)</th>
			<th>T7E1 images</th>
			<th>Phenotype files</th>
			</thead>
			<tbody>
			<!-- for microinjections of this gRNA -->
			{% for inx,files in inxDict.items %}
			<tr>
			<td><a href="{% url 'data:uInx-detail' inx.pk %}">{{inx.date}}</a></td>
			<td>
			{% if inx.inxsurvivalexp %}
			<a href="{% url 'data:inxSurvExp-detail' inx.inxsurvivalexp.pk %}">{{inx.inxsurvivalexp.nInx}} embryos</a>
			{% else %}
			No survival data
			{% endif %}
			</td>
			<td>
			{% if files.T7E1GelSet %}
				<ul>
				{% for T7E1 in files.T7E1GelSet %}
				<li><a href="{% url 'data:gel-detail' T7E1.pk %}">{{T7E1.shortName}}</a></li>
				{% endfor %}
				</ul>
			{% else %}
			No T7E1 uploaded
			{% endif %}
			</td>
			<td>
			{% if files.expInfoSet %}
				<ul>
				{% for expInfo in files.expInfoSet %}
				<li><a href="{% url 'data:file-detail' expInfo.pk %}">{{expInfo.shortName}}</a></li>
				{% endfor %}
				</ul>
			{% else %}
			No expInfos uploaded
			{% endif %}
			</td>
			</tr>
			{% endfor %}
			</tbody>
			</table>
			{% else %}
			<p>No injections found for this particular gRNA, though it has been made or received.</p>
			{% endif %}
			</li>
		{% endfor %}
	</ul>
	{% else %}
	No good queries; try harder next time!
	{% endif %}
	</div>
</div>
</div>
</div>
{% endif %}
{{block.super}}
</div>
{% endblock %}
<!--{% if queryString %}
<p>You searched for "{{ queryString }}" and the results are listed below.</p>
<p>
{% for obj in found_obj %}
<li>{{ obj }}</li>
{% endfor %}
{% endif %}-->