LabNB/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from LabNB import views     # This lets us use the custom error handlers, as well as an index view with context, if desired.

# These handlers override the default error page provided by Django.
# Django looks for these var names specifically in the urlconf.

handler404 = 'LabNB.views.page_not_found'
handler500 = 'LabNB.views.server_error'

# Added for simple templates like homepage, or icons
from django.views.generic import TemplateView, RedirectView

# URLs
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'LabNB.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # http://stackoverflow.com/questions/1940528/django-index-page-best-most-common-practice

    # OMG CRAZY NOTE: namespace ABSOLUTELY MUST BE IN DOUBLEQUOTES to work.
    
    url(r'^$', views.index, name='index'),
    url(r'accounts/login/', 'django.contrib.auth.views.login'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^labinv/', include('labinv.urls', namespace="labinv")),
    url(r'^data/', include('data.urls', namespace="data")),
    url(r'^apple-touch-icon\.png$', RedirectView.as_view(
        url='%simg/apple-touch-icon.png' % settings.STATIC_URL)),
    url(r'^crossdomain\.xml$', TemplateView.as_view(
	   template_name='crossdomain.xml')),
    url(r'^favicon\.ico$', RedirectView.as_view(
	   url='%simg/favicon.ico' % settings.STATIC_URL)),
    url(r'^humans\.txt', TemplateView.as_view(
	   template_name='humans.txt')),
	url(r'^robots\.txt', TemplateView.as_view(
		template_name='robots.txt')),
)

urlpatterns += patterns('', (
        r'^static/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}
))

urlpatterns += patterns('',
               (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                 {'document_root': settings.MEDIA_ROOT}),
              )

data/urls.py
from django.conf.urls import patterns,url
from data import views
from django.conf import settings
from django.contrib.auth.decorators import login_required

# To use url tag in template, use something like {% url 'data:URLNAME' %}

urlpatterns = patterns('',
	# url(r'accounts/login/', 'django.contrib.auth.views.login'),
	url(r'^$', views.index, name='index'),
	url(r'^inxSurvExp/$', views.inxSurvExpList, name='inxSurvExp-list'),
	url(r'^inxSurvExp/create$', login_required(views.inxSurvExpCreateView.as_view()), name='inxSurvExp-create'),
	url(r'^inxSurvExp/(?P<pk>\d+)/inxsurvplot.png$', views.inxSurvExpPlot, name='inxSurvExp-plot'),
	url(r'^inxSurvExp/(?P<pk>\d+)$', views.inxSurvExpDetail, name='inxSurvExp-detail'),
	url(r'^inxSurvExp/(?P<pk>\d+)/update$', login_required(views.inxSurvExpUpdateView.as_view()), name='inxSurvExp-update'),
	url(r'^inxSurvExp/(?P<pk>\d+)/delete$', login_required(views.inxSurvExpDeleteView.as_view()), name='inxSurvExp-delete'),
	url(r'^survExp/$', views.survExpList, name='survExp-list'),
	url(r'^survExp/create$', login_required(views.survExpCreateView.as_view()), name='survExp-create'),
	url(r'^survExp/(?P<pk>\d+)/survplot.png$', views.survExpPlot, name='survExp-plot'),
	url(r'^survExp/(?P<pk>\d+)$', views.survExpDetail, name='survExp-detail'),
	url(r'^survExp/(?P<pk>\d+)/update$', login_required(views.survExpUpdateView.as_view()), name='survExp-update'),
	url(r'^survExp/(?P<pk>\d+)/delete$', login_required(views.survExpDeleteView.as_view()), name='survExp-delete'),
	url(r'^uInx/$', views.uInxList, name='uInx-list'),
	url(r'^uInx/create$', login_required(views.uInxCreateView.as_view()), name='uInx-create'),
	url(r'^uInx/(?P<pk>\d+)$', views.uInxDetail, name='uInx-detail'),
	url(r'^uInx/(?P<pk>\d+)/update$', login_required(views.uInxUpdateView.as_view()), name='uInx-update'),
	url(r'^uInx/(?P<pk>\d+)/delete$', login_required(views.uInxDeleteView.as_view()), name='uInx-delete'),
	url(r'^exp/$', views.miscExpList, name='exp-list'),
	url(r'^exp/create$', login_required(views.miscExpCreateView.as_view()), name='exp-create'),
	url(r'^exp/(?P<pk>\d+)$', views.miscExpDetail, name='exp-detail'),
	url(r'^exp/(?P<pk>\d+)/update$', login_required(views.miscExpUpdateView.as_view()), name='exp-update'),
	url(r'^exp/(?P<pk>\d+)/delete$', login_required(views.miscExpDeleteView.as_view()), name='exp-delete'),
	url(r'^gel/$', views.gelList, name='gel-list'),
	url(r'^gel/create$', login_required(views.gelCreateView.as_view()), name='gel-create'),
	url(r'^gel/(?P<pk>\d+)$', views.gelDetail, name='gel-detail'),
	url(r'^gel/(?P<pk>\d+)/update$', login_required(views.gelUpdateView.as_view()), name='gel-update'),
	url(r'^gel/(?P<pk>\d+)/delete$', login_required(views.gelDeleteView.as_view()), name='gel-delete'),
	url(r'^img/$', views.miscImgList, name='img-list'),
	url(r'^img/create$', login_required(views.miscImgCreateView.as_view()), name='img-create'),
	url(r'^img/(?P<pk>\d+)$', views.miscImgDetail, name='img-detail'),
	url(r'^img/(?P<pk>\d+)/update$', login_required(views.miscImgUpdateView.as_view()), name='img-update'),
	url(r'^img/(?P<pk>\d+)/delete$', login_required(views.miscImgDeleteView.as_view()), name='img-delete'),
	url(r'^file/$', views.miscFileList, name='file-list'),
	url(r'^file/create$', login_required(views.miscFileCreateView.as_view()), name='file-create'),
	url(r'^file/(?P<pk>\d+)$', views.miscFileDetail, name='file-detail'),
	url(r'^file/(?P<pk>\d+)/update$', login_required(views.miscFileUpdateView.as_view()), name='file-update'),
	url(r'^file/(?P<pk>\d+)/delete$', login_required(views.miscFileDeleteView.as_view()), name='file-delete'),
	url(r'^custom/querydata$',views.queryData,name='querydata'),
	)

urlpatterns += patterns('', (
        r'^static/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}
)
)

urlpatterns += patterns('',
               (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                 {'document_root': settings.MEDIA_ROOT}),
              )

LabNB/views.py
from django.views import defaults
from django.shortcuts import render
from django.http import HttpResponse
from django.template import Context, loader
from django.contrib.auth.decorators import login_required

def page_not_found(request):
	"""Handle the server_error view"""
	return defaults.page_not_found(request, template_name='404.html')

def server_error(request):
	"""Handle the server_error view"""
	return defaults.server_error(request, template_name='500.html')

@login_required
def index(request):
	t = loader.get_template('index.html')
	C=Context()
	return HttpResponse(t.render(C))

templates/LabNB/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="{% static 'img/apple-touch-icon.png' %}">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
        {% block head %}{% endblock %}
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
            <a class="navbar-brand" href="/">Lab Notebook</a>
            <a class="navbar-brand" href="/labinv">Inventory</a>
            <a class="navbar-brand" href="/data">Data</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                {% comment %}
                <form class="navbar-form navbar-right" role="form">
                <div class="form-group">
                    <input type="text" placeholder="Username" class="form-control">
                </div>
                <div class="form-group">
                    <input type="password" placeholder="Password" class="form-control">
                </div>
                <button type="submit" class="btn btn-success">Sign in</button>
                </form>
                {% endcomment %}
            </div><!--/.navbar-collapse -->
        </div>
    </nav>

    {% block content %}
    <hr>    
    <footer>
        <!--[if lte IE 8]><span style="filter: FlipH; -ms-filter: "FlipH"; display: inline-block;"><![endif]-->
        <span style="-moz-transform: scaleX(-1); -o-transform: scaleX(-1); -webkit-transform: scaleX(-1); transform: scaleX(-1); display: inline-block;">
        &copy</span> Parth Lakhani 2015; <a href="https://github.com/prlakhani/LabNB/blob/master/LICENSE.md">GPL v3.0</a>
        
        <!--[if lte IE 8]></span><![endif]-->
    </footer>
    {% endblock %}
    
    <!-- /container -->        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"><\/script>')</script>

        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>

        <script src="{% static 'js/plugins.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
    </body>
</html>

templates/LabNB/index.html
{% extends "base.html" %}

{% block title %}Lab Notebook Home{% endblock title %}

{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1>Hi Parth!</h1>
            <p>This is your lab notebook. Make sure you use it regularly!</p>
            <p><a class="btn btn-primary btn-lg" href="{% url 'index' %}" role="button">Learn more &raquo;</a></p>
        </div>
    </div>

    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-6">
                <h2>Lab Inventory</h2>
                <p>Go here to add tubes or aliquots of various sorts, and PCR strips.</p>
                <p><a class="btn btn-default" href="{% url 'labinv:index' %}" role="button">Go &raquo;</a></p>
            </div>
            <div class="col-md-6">
                <h2>Data</h2>
                <p>Go here to add images or other raw data, as well as information about experiments.</p>
                <p><a class="btn btn-default" href="{% url 'data:index' %}" role="button">Go &raquo;</a></p>
            </div>
        </div>
        {{ block.super }}
    </div>
    
{% endblock content %}